/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Training' at '7/5/16 2:14 PM' with Gradle 2.13
 *
 * @author Training, @date 7/5/16 2:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
